name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'  # You can set a specific Flutter version, replace it with the latest or desired version

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
